### ISSUE TITLE
variables mismatch between cfg and scripts

### ISSUE THREAD

**Issue by t1n1wall** [tedsluis/dump1090.socket30003#5]
socket30003.cfg  uses a variable of 

datadirectory

and rangeview.pl + heatmap.pl use

defaultdatadirectory , so they don't pickup the setting

**Comment by tedsluis** [comment]
Hi t1n1wall,  This was fixed some time ago (7 July 2016):  https://github.com/tedsluis/dump1090.socket30003/commit/4b191e6ac8948fb92eeff7d480ab05f1187c5864

Sorry for the late response,

Regards,

Ted
